name: Compile and release

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  PLUGIN_NAME: deathrun
  SCRIPTS_PATH: addons/sourcemod/scripting

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.12.x' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download include files
        run: |
          set -euo pipefail
          mkdir -p "${{ env.SCRIPTS_PATH }}/include"

          includes=(
            "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc"
            "https://raw.githubusercontent.com/nosoop/SM-TFEconData/master/scripting/include/tf_econ_data.inc"
            "https://raw.githubusercontent.com/Mikusch/PluginStateManager/refs/heads/master/addons/sourcemod/scripting/include/pluginstatemanager.inc"
            "https://raw.githubusercontent.com/DoctorMcKay/sourcemod-plugins/master/scripting/include/morecolors.inc"
          )

          for url in "${includes[@]}"; do
            echo "Downloading $url"
            curl -fsSL -O --output-dir "${{ env.SCRIPTS_PATH }}/include" "$url"
          done

      - name: Setup SourcePawn Compiler ${{ matrix.sm-version }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}
          version-file: ${{ env.SCRIPTS_PATH }}/${{ env.PLUGIN_NAME }}.sp
          define-name: PLUGIN_VERSION

      - name: Compile plugin
        run: |
          set -euo pipefail
          mkdir -p ../plugins
          spcomp -v2 -E -i "include" -o "../plugins/${{ env.PLUGIN_NAME }}.smx" "${{ env.PLUGIN_NAME }}.sp"
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-${{ matrix.sm-version }}
          path: addons/sourcemod/plugins/${{ env.PLUGIN_NAME }}.smx
          if-no-files-found: error

      - name: Zip output
        if: github.event_name != 'pull_request'
        run: zip -qq -r "${{ github.event.repository.name }}.zip" addons/sourcemod

      - name: Create GitHub Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: ./${{ github.event.repository.name }}.zip
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true
          skipIfReleaseExists: true
